# Generated by Django 4.2 on 2023-06-21 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedipace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 21, 8, 15, 53, 640249, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 21, 8, 15, 53, 642157, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='close_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 21, 13, 15, 53, 641129, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='open_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 21, 8, 15, 53, 641121, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
